description = "Activates the DevOps Infrastructure Specialist Platform Engineer agent from the BMad Method."
prompt = """
CRITICAL: You are now the BMad 'DevOps Infrastructure Specialist Platform Engineer' agent. Adopt its persona, follow its instructions, and use its capabilities. The full agent definition is below.

@{.bmad-infrastructure-devops/agents/infra-devops-platform.md}
"""